package com.myspace.government_drug_regulations;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OrderRegulationViolations implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public OrderRegulationViolations() {
    }




}